In [5]:
import pandas as pd
import numpy as np
import os

In [9]:
os.getcwd()

'c:\\Users\\A_Bazhenova\\OneDrive - Domino Printing Sciences\\Documents\\0_my_documents\\0_projects\\6_enps\\enps_dash_app\\notebooks'

In [11]:
#data = pd.read_excel("../data/raw/global eNPS responses_June 2023.xlsx")
data = pd.read_csv("../data/raw/eNPS - Feb 2023 - all results.csv")

In [12]:
data

,Survey Question Response ID,Question Title,Scale Score,Question Comment,Survey Response: Team Member: HR Department: Policy: Policy Name,Survey Response: Team Member: Gender,Survey Response: Team Member: Current Employment: Division,Survey Response: Team Member: Current Employment: Service Years,Survey Response: Team Member: Current Employment: Department,Survey Response: Team Member: Company,Survey Response: Team Member: Function,Survey Response: Team Member: Country,Survey Response: Team Member: Manager: Name
0,a3h8e0000008WN2,이렇게 평가한 가장 큰 이유는 무엇입니까?,NaN,직원들에 대한 처우 및 대우는 좋은 편이나 잡다한 일이나 업무가 너무 많음. 특히 ...,Korea,Male,Coding & Marking,5,Field Based Service,Domino Korea Pte Ltd,Service,"Korea, Republic Of",심민욱 Shim
1,a3h8e0000008WN1,도미노를직장으로 추천할 가능성이 얼마나 됩니까? 0부터10까지 척도로 표시해 주십시오,7.0,NaN,Korea,Male,Coding & Marking,5,Field Based Service,Domino Korea Pte Ltd,Service,"Korea, Republic Of",심민욱 Shim
2,a3h8e0000008WMx,选择该分值的主要原因是什么？,NaN,8,China DPT,Male,Coding & Marking,1,Facilities,Domino Printing Technology Ltd,Administration,China,Jeanva Liang
3,a3h8e0000008WMw,在从0到10的范围内，您推荐Domino作为工作场所的可能性有多大？,-1.0,NaN,China DPT,Male,Coding & Marking,1,Facilities,Domino Printing Technology Ltd,Administration,China,Jeanva Liang
4,a3h8e0000008WMs,이렇게 평가한 가장 큰 이유는 무엇입니까?,NaN,사측의 업계 최고 대우와 직원복지에 지속적인 관심.,Korea,Male,Coding & Marking,13,Sales,Domino Korea Pte Ltd,Selling & Distribution,"Korea, Republic Of",주영철 Joo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4321,a3h8e0000004J2d,On a scale from 0 to 10 how likely are you to ...,7.0,NaN,India,Male,Coding & Marking,5,Planning,Domino Printech India LLP,Indirect Manufacturing Printers,India,Ratheesh K
4322,a3h8e0000004J2Z,What's the primary reason for your score?,NaN,Work culture and environment is very good.,India,Male,Coding & Marking,9,General Management/Admin,Domino Printech India LLP,Sales Support,India,Ratheesh K
4323,a3h8e0000004J2Y,On a scale from 0 to 10 how likely are you to ...,9.0,NaN,India,Male,Coding & Marking,9,General Management/Admin,Domino Printech India LLP,Sales Support,India,Ratheesh K
4324,a3h8e0000004J2U,¿Cuál ha sido el motivo que te ha llevado a se...,NaN,"Se nos excluyen de muchas actividades por ""no ...",Mexico,Female,Coding & Marking,4,Aftermarket,Domino Printing Mexico SA de CV,Selling & Distribution,Mexico,Brenda Karaszewski
4325,a3h8e0000004J2T,"En una escala del 0 al 10, ¿Recomendarías Domi...",7.0,NaN,Mexico,Female,Coding & Marking,4,Aftermarket,Domino Printing Mexico SA de CV,Selling & Distribution,Mexico,Brenda Karaszewski

In [13]:
list(data.columns)

['Survey Question Response ID',
 'Question Title',
 'Scale Score',
 'Question Comment',
 'Survey Response: Team Member: HR Department: Policy: Policy Name',
 'Survey Response: Team Member: Gender',
 'Survey Response: Team Member: Current Employment: Division',
 'Survey Response: Team Member: Current Employment: Service Years',
 'Survey Response: Team Member: Current Employment: Department',
 'Survey Response: Team Member: Company',
 'Survey Response: Team Member: Function',
 'Survey Response: Team Member: Country',
 'Survey Response: Team Member: Manager: Name']

In [14]:
['index', 'Question Title', 'Scale Score']+[c for c in data.columns if c not in ['index', 'Question Title', 'Scale Score']]

['index',
 'Question Title',
 'Scale Score',
 'Survey Question Response ID',
 'Question Comment',
 'Survey Response: Team Member: HR Department: Policy: Policy Name',
 'Survey Response: Team Member: Gender',
 'Survey Response: Team Member: Current Employment: Division',
 'Survey Response: Team Member: Current Employment: Service Years',
 'Survey Response: Team Member: Current Employment: Department',
 'Survey Response: Team Member: Company',
 'Survey Response: Team Member: Function',
 'Survey Response: Team Member: Country',
 'Survey Response: Team Member: Manager: Name']

In [15]:
def data_reshaping(data):
    
    if ~data['Scale Score'].isnull()[0]:
        data['Score or Comment'] = ['Score', 'Comment']*int(len(data)/2)
        data_comments = data.loc[list(range(1, len(data), 2))].reset_index().rename(columns={'index':'Comment Original Index', 'Question Title':'Comment Question Title'})
        data_scores = data.loc[list(range(0, len(data), 2))].reset_index().rename(columns={'index':'Score Original Index', 'Question Title':'Score Question Title'})
        
    else:
        data['Score or Comment'] = ['Comment', 'Score']*int(len(data)/2)
        data_comments = data.loc[list(range(0, len(data), 2))].reset_index().rename(columns={'index':'Comment Original Index', 'Question Title':'Comment Question Title'})
        data_scores = data.loc[list(range(1, len(data), 2))].reset_index().rename(columns={'index':'Score Original Index', 'Question Title':'Score Question Title'})
    
    data_wide = pd.concat([data_scores[['Score Original Index', 'Score Question Title', 'Scale Score']], data_comments[[c for c in data_comments.columns if c not in ['Score Original Index', 'Score Question Title', 'Scale Score', 'Score or Comment']]]], axis=1)
    
    return data_wide

In [17]:
df = data_reshaping(data)
df

,Score Original Index,Score Question Title,Scale Score,Comment Original Index,Comment Question Title,Question Comment,Question Response #,Survey Response: Team Member: Function,Survey Response: Team Member: Current Employment: Contract Type
0,1,On a scale from 0 to 10 how likely are you to ...,10.0,0,What's the primary reason for your score?,Happy doing my job,SQR-2023.06 #47652,Service,Permanent
1,3,"Numa escala de 0 a 10, qual a probabilidade de...",4.0,2,Qual é o principal motivo da sua pontuação?,Desde que a administração está foçada em Espan...,SQR-2023.06 #47650,Indirect Manufacturing Fluids,Fixed Term Contract
2,5,"Sur une échelle de 0 à 10, quelle est la proba...",10.0,4,Quelle est la raison principale de votre score?,Possibilité d'évolution,SQR-2023.06 #47648,Service,Permanent
3,7,"En una escala del 0 al 10, ¿Recomendarías Domi...",9.0,6,¿Cuál ha sido el motivo que te ha llevado a se...,Traspasar toda la información o especificacion...,SQR-2023.06 #47646,Service,Permanent
4,9,"En una escala del 0 al 10, ¿Recomendarías Domi...",9.0,8,¿Cuál ha sido el motivo que te ha llevado a se...,Como bien se comentó la última vez…el dormir f...,SQR-2023.06 #47644,Service,Permanent
...,...,...,...,...,...,...,...,...,...
2045,4091,在从0到10的范围内，您推荐Domino作为工作场所的可能性有多大？,9.0,4090,选择该分值的主要原因是什么？,工作环境，学习机会,SQR-2023.06 #43546,Indirect Manufacturing Printers,Permanent
2046,4093,在从0到10的范围内，您推荐Domino作为工作场所的可能性有多大？,5.0,4092,选择该分值的主要原因是什么？,工资薪水低，福利待遇差，自我发展空间小,SQR-2023.06 #43544,Direct Manufacturing Printers,Permanent
2047,4095,在从0到10的范围内，您推荐Domino作为工作场所的可能性有多大？,10.0,4094,选择该分值的主要原因是什么？,公司文化和工作氛围非常棒,SQR-2023.06 #43542,Selling & Distribution,Permanent
2048,4097,在从0到10的范围内，您推荐Domino作为工作场所的可能性有多大？,6.0,4096,选择该分值的主要原因是什么？,无,SQR-2023.06 #43540,Sales Support,Permanent
2049,4099,在从0到10的范围内，您推荐Domino作为工作场所的可能性有多大？,10.0,4098,选择该分值的主要原因是什么？,NaN,SQR-2023.06 #43538,Administration,Permanent